import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import Footer from "./layout/footer";
import "./styles/quiz.scss";

const noto = Noto_Sans_JP ({
    weight: ["400", "700", "900"],
    style: "normal",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Frontend Engineer L.T's Portfolio - Supabase(BaaS) & React",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={noto.className}>
                {children}
                <Footer />
            </body>
        </html>
    );
}
