import type { Metadata } from "next";
import { createClient } from '@/utils/supabase/server';
import OpeningBg from './components/openingBg';
import Container from "./components/container";

export const metadata: Metadata = {
    title: "Frontend Engineer L.T's Portfolio - Supabase(BaaS) & React",
    description: "Generated by create next app",
};

export default async function Home() {
    const supabase = createClient(); 
    const { data: QUIZ }       = await supabase.from('nextjs-quiz')
        .select('*')
        .order('id', { ascending: true })
    const { data: DB, error } = await supabase.from('nextjs-quiz-choices')
        .select('*')

    return(
        <main className="flex flex-col items-center justify-between p-24">
            <OpeningBg></OpeningBg>
            <Container QUIZ={QUIZ} DB={DB}></Container>
        </main>
    )
}

